CREATE DATABASE BookMyShow

USE BookMyShow

CREATE TABLE CUSTOMER(
CustomerID INT IDENTITY(100,1),
CustomerName VARCHAR(50) NOT NULL,
CustomerPhone BIGINT NOT NULL,
CustomerEmail VARCHAR(20) NOT NULL,
CONSTRAINT PK_CUSTOMER PRIMARY KEY(CustomerID)
)

CREATE TABLE CITY(
CityID INT IDENTITY(200,1),
CityName VARCHAR(30) NOT NULL,
CONSTRAINT PK_CITY PRIMARY KEY(CityID)
)


CREATE TABLE THEATER(
TheaterID INT IDENTITY(300,1),
TheaterName VARCHAR(30) NOT NULL,
CityID INT NOT NULL,
CONSTRAINT PK_THEATER PRIMARY KEY(TheaterID),
CONSTRAINT FK_THEATER_CITY FOREIGN KEY(CityID) REFERENCES CITY(CityID)
)

CREATE TABLE MOVIE(
MovieID INT IDENTITY(400,1),
MovieTitle VARCHAR(60) NOT NULL,
Duration TIME NOT NULL,
Releasedate DATE NOT NULL,
MovieDescription VARCHAR(30),
CONSTRAINT PK_MOVIE PRIMARY KEY(MovieID)
)



CREATE TABLE LANGUAGE(
LanguageID INT IDENTITY(500,1),
LanguageName VARCHAR(30) NOT NULL,
CONSTRAINT PK_LANGUAGE PRIMARY KEY(LanguageID)
)

CREATE TABLE GENRE(
GenreID INT IDENTITY(600,1),
GenreName VARCHAR(30) NOT NULL,
CONSTRAINT PK_GENRE PRIMARY KEY(GenreID)
)

CREATE TABLE MOVIELANGUAGE(
MovieLangID	INT IDENTITY(700,1),
MovieID	INT NOT NULL,
LanguageID	INT NOT NULL,
CONSTRAINT PK_MOVIELANGUAGE PRIMARY KEY(MovieLangID),
CONSTRAINT FK_MOVIELANGUAGE_MOVIE FOREIGN KEY(MovieID) REFERENCES MOVIE(MovieID),
CONSTRAINT FK_MOVIELANGUAGE_LANGUAGE FOREIGN KEY(LanguageID) REFERENCES LANGUAGE(LanguageID)
)

CREATE TABLE MOVIEGENRE(
MovieGenreID INT IDENTITY(800,1),
MovieID	INT NOT NULL,
GenreID	INT NOT NULL,
CONSTRAINT PK_MOVIEGENRE PRIMARY KEY(MovieGenreID),
CONSTRAINT FK_MOVIEGENRE_MOVIE FOREIGN KEY(MovieID) REFERENCES MOVIE(MovieID),
CONSTRAINT FK_MOVIEGENRE_GENRE FOREIGN KEY(GenreID) REFERENCES GENRE(GenreID)
)

CREATE TABLE REVIEW(
ReviewID INT IDENTITY(900,1),
CustomerID INT NOT NULL,
MovieLangID	INT NOT NULL,
Review	VARCHAR NOT NULL,
CONSTRAINT PK_REVIEW PRIMARY KEY(ReviewID),
CONSTRAINT FK_REVIEW_CUSTOMER FOREIGN KEY(CustomerID) REFERENCES CUSTOMER(CustomerID),
CONSTRAINT FK_REVIEW_MOVIELANGUAGE FOREIGN KEY(MovieLangID) REFERENCES MOVIELANGUAGE(MovieLangID)
)

CREATE TABLE SCREEN(
ScreenID INT IDENTITY(1000,1),
ScreenName VARCHAR(30) NOT NULL,
TheaterID INT NOT NULL ,
CONSTRAINT PK_SCREEN PRIMARY KEY(ScreenID),
CONSTRAINT FK_SCREEN_THEATER FOREIGN KEY(TheaterID) REFERENCES THEATER(TheaterID)
)

CREATE TABLE SHOW(
ShowID INT IDENTITY(1100,1),
ShowStartTime TIME NOT NULL,
ShowDate DATE NOT NULL,
TheaterID INT NOT NULL,
MovieLangID INT NOT NULL,
ScreenID INT NOT NULL,
CONSTRAINT PK_SHOW PRIMARY KEY(ShowID),
CONSTRAINT FK_SHOW_THEATER FOREIGN KEY(TheaterID) REFERENCES THEATER(TheaterID),
CONSTRAINT FK_SHOW_MOVIELANGUAGE FOREIGN KEY(MovieLangID) REFERENCES MOVIELANGUAGE(MovieLangID),
CONSTRAINT FK_SHOW_SCREEN FOREIGN KEY(ScreenID) REFERENCES SCREEN(ScreenID)
)

CREATE TABLE SEATTYPE(
SeatTypeID INT IDENTITY(1200,1),
SeatTypeName VARCHAR(20) NOT NULL,
Seatprice DECIMAL(4,2) NOT NULL,
CONSTRAINT PK_SEATTYPE PRIMARY KEY(SeatTypeID)
)

CREATE TABLE SEAT(
SeatID INT IDENTITY(1300,1),
SeatTypeID INT NOT NULL,
ScreenID INT NOT NULL,
CONSTRAINT PK_SEAT PRIMARY KEY(SeatID),
CONSTRAINT FK_SEAT_SEATTYPE FOREIGN KEY(SeatTypeID) REFERENCES SEATTYPE(SeatTypeID),
CONSTRAINT FK_SEAT_SCREEN FOREIGN KEY(ScreenID) REFERENCES SCREEN(ScreenID)
)


CREATE TABLE BOOKING(
BookingID INT IDENTITY(1400,1),
CustomerID INT NOT NULL,
ShowID INT NOT NULL,
Boookingdate DATE NOT NULL,
TotalAmount	DECIMAL(5,2) NOT NULL,
CONSTRAINT PK_BOOKING PRIMARY KEY(BookingID),
CONSTRAINT FK_BOOKING_CUSTOMER FOREIGN KEY(CustomerID) REFERENCES CUSTOMER(CustomerID),
CONSTRAINT FK_BOOKING_SHOW FOREIGN KEY(ShowID) REFERENCES SHOW(ShowID)
)
alter table BOOKING alter column TotalAmount DECIMAL(7,2) NOT NULL


CREATE TABLE BOOKEDSEAT(
BookedSeatID INT IDENTITY(1500,1),
SeatID INT NOT NULL,
BookingID INT NOT NULL,
CONSTRAINT PK_BOOKEDSEAT PRIMARY KEY(BookedSeatID),
CONSTRAINT FK_BOOKEDSEAT_SEAT FOREIGN KEY(SeatID) REFERENCES SEAT(SeatID),
CONSTRAINT FK_BOOKEDSEAT_BOOKING FOREIGN KEY(BookingID) REFERENCES BOOKING(BookingID)
)

CREATE TABLE PAYMENTMETHOD(
PayMethodID	INT IDENTITY(1600,1),
PayMethodName VARCHAR(25),
CONSTRAINT PK_PAYMENTMETHOD PRIMARY KEY(PayMethodID)
)


CREATE TABLE PAYMENT(
PaymentID INT IDENTITY(1700,1),
BookingID INT NOT NULL,
PayMethodID INT NOT NULL,
CONSTRAINT PK_PAYMENT PRIMARY KEY(PaymentID),
CONSTRAINT FK_PAYMENT_BOOKING FOREIGN KEY(BookingID) REFERENCES BOOKING(BookingID),
CONSTRAINT FK_PAYMENT_PAYMENTMETHOD FOREIGN KEY(PayMethodID) REFERENCES PAYMENTMETHOD(PayMethodID)
)

select * from CUSTOMER
select * from CITY
select * from GENRE
select * from LANGUAGE
SELECT * FROM SEATTYPE

select * from MOVIE
select * from MOVIEGENRE
select * from MOVIELANGUAGE


select * from THEATER
select * from SCREEN
select * from SEAT

select * from SHOW

select * from PAYMENTMETHOD

select * from BOOKING
select * from BOOKEDSEAT
select * from PAYMENT